services:
  officehours:
    build: .
    container_name: officehours
    restart: unless-stopped
    ports:
      - '3000:3000'
    volumes:
      - '/home/youboon2/projects/officehours-node/.env.docker:/usr/src/app/.env'
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    container_name: mysql
    restart: unless-stopped
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: officehours
      MYSQL_USER: officehours
      MYSQL_PASSWORD: password
      MYSQL_RANDOM_ROOT_PASSWORD: fact
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          'ping',
          '-h',
          'localhost',
          '-uofficehours',
          '-ppassword',
        ]
      interval: 5s
      timeout: 5s
      retries: 20

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: unless-stopped
    ports:
      - '8080:80'
    environment:
      PMA_ARBITRARY: 1
